version: "3"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
  idea:
    image: idea
    container_name: idea_app
    ports:
      - 8080:8080
    depends_on:
      - mongodb