---
spring:
  rabbitmq:
    host: localhost
    port: 5672
  mail:
    host: "smtp.yandex.ru"
    username: springapplication@yandex.ru
    password: vuolmfprzkknmctq
    port: 465
    protocol: "smtps"
    default-encoding: "UTF-8"
  config:
    activate:
      on-profile: dev
server:
  port: 8082
---
spring:
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
  mail:
    host: "smtp.yandex.ru"
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    port: 465
    protocol: "smtps"
    default-encoding: "UTF-8"
  config:
    activate:
      on-profile: prod
server:
  port: ${SERVER_PORT}