spring:
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
---
spring:
  config:
    activate:
      on-profile: prod
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
server:
  port: ${SERVER_PORT}
---
spring:
  config:
    activate:
      on-profile: dev
  rabbitmq:
    host: localhost
    port: 5672
server:
  port: 8080
userService:
  port: 8083
allowedOrigin: http://localhost:4200
grpc:
  client:
    GLOBAL:
      negotiation-type: PLAINTEXT # fix it