---
spring:
  config:
    activate:
      on-profile: dev
  rabbitmq:
    host: "127.0.0.1"
    port: 5672

server:
  port: 8085

---
spring:
  config:
    activate:
      on-profile: prod
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}

server:
  port: ${SERVER_PORT}