apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: ex72-app
  ports:
  - port: 8888
    name: backend
    targetPort: 8080
  - port: 8887
    name: emailer
    targetPort: 8081
  - port: 9092
    name: kafka
    targetPort: 9092
  - port: 2181
    name: zookeeper
    targetPort: 2181
---
apiVersion: v1
kind: Service
metadata:
  name: rdb-service
spec:
  clusterIP: None
  ports:
  - port: 3306
---
apiVersion: v1
kind: Endpoints
metadata:
  name: rdb-endpoint
subsets:
  - addresses:
    - ip: 52.255.201.87
    ports:
      - port: 3306
        name: rdb-service