spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB

server:
  port: ${SERVER_PORT}

allowedOrigin: http://localhost:4200
uploadPath: ${RESOURCE_PATH}

kafka:
  emailTopic: emailTopic
  bootstrap-servers: localhost:9092