spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/ex72
    username: local
    password: local
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB

server:
  port: 8080

allowedOrigin: http://localhost:4200
uploadPath: /home/koshey/IdeaProjects/Ex72/frontend/src/assets/uploaded

kafka:
  emailTopic: emailTopic
  bootstrap-servers: localhost:9092