spring:
  rabbitmq:
    host: localhost
    port: 5672
  config:
    activate:
      on-profile: dev
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/idea
    username: root
    password: root
server:
  port: 8083
---
spring:
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
  config:
    activate:
      on-profile: prod
server:
  port: ${SERVER_PORT}